# docker-compose.debug.yml

services:
  api:
    build:
      context: .
      target: development
    ports:
      - "5678:5678"
    entrypoint: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client"]
    command: ["-m", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "9500"]

  worker:
    build:
      context: .
      target: development
    ports:
      - "5679:5679"
    entrypoint: ["python", "-m", "debugpy", "--listen", "0.0.0.0:5679", "--wait-for-client"]
    command: ["-m", "arq", "api.worker_settings.WorkerSettings"]