# docker-compose.yml

services:
  redis:
    image: redis:alpine
    container_name: creative-catalyst-redis
    ports:
      - "6379:6379"

  # --- START: DEFINITIVE CHROMA SERVICE REFACTOR ---
  chroma:
    image: chromadb/chroma:latest
    container_name: creative-catalyst-chroma
    ports:
      # This maps the EXTERNAL port on your Mac to the INTERNAL port 8000.
      # It will use the value of CHROMA_EXTERNAL_PORT from your .env file,
      # or default to 8000 if it's not set.
      - "${CHROMA_EXTERNAL_PORT:-8000}:8000"
    volumes:
      - ./chroma_cache:/chroma/.chroma/server/
  # --- END: DEFINITIVE CHROMA SERVICE REFACTOR ---

  api:
    build: .
    container_name: creative-catalyst-api
    ports:
      - "9500:9500"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - chroma

  worker:
    build: .
    container_name: creative-catalyst-worker
    command: /usr/local/bin/arq api.worker_settings.WorkerSettings
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - chroma

  clear-cache:
    build: .
    command: ["clear_cache.py", "-y"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis