# docker-compose.yml

services:
  redis:
    image: redis:alpine
    container_name: creative-catalyst-redis
    ports:
      - "6379:6379"
    profiles: ["app"]

  chroma:
    image: chromadb/chroma:latest
    container_name: creative-catalyst-chroma
    ports:
      - "${CHROMA_EXTERNAL_PORT:-8000}:8000"
    volumes:
      - ./chroma_cache:/chroma/.chroma/server/
    profiles: ["app"]

  api:
    build: .
    container_name: creative-catalyst-api
    ports:
      - "9500:9500"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      chroma:
        condition: service_started
    profiles: ["app"]

  worker:
    build: .
    container_name: creative-catalyst-worker
    command: /usr/local/bin/arq api.worker_settings.WorkerSettings
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      chroma:
        condition: service_started
    profiles: ["app"]

  clear-cache:
    build: .
    entrypoint: ""
    command: ["python", "-m", "clear_cache", "-y"]
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    profiles: ["tasks"]