# catalyst/pipeline/processors/generation.py

import base64
import json
from pathlib import Path
from openai import AsyncOpenAI

from catalyst.pipeline.base_processor import BaseProcessor
from catalyst.context import RunContext
from ... import settings


class DalleImageGenerationProcessor(BaseProcessor):
    """
    The final pipeline step. Takes the generated prompts from the context
    and calls the GPT Image API to generate and save the final images.
    """

    def __init__(self):
        super().__init__()
        self.client = AsyncOpenAI(api_key=settings.DALLE_API_KEY)

    async def process(self, context: RunContext) -> RunContext:
        """
        Iterates through the final prompts and generates an image for each.
        """
        self.logger.info("🎨 Starting GPT Image generation...")

        if not context.final_report.get("detailed_key_pieces"):
            self.logger.warning(
                "⚠️ No key pieces found in the report. Skipping image generation."
            )
            return context

        # --- START OF FIX: IMPROVED PROMPT LOADING ---
        # The prompts are now generated by a processor that runs before this one.
        # We should reliably get them from the context artifacts.
        # The FinalOutputGeneratorProcessor saves its result to the context, but we need to
        # access the prompts specifically. Let's assume the prompts are in a known key.
        # We will add a step in FinalOutputGeneratorProcessor to save prompts to context.
        # For now, we'll rely on the file-based fallback which is more robust.
        prompts_data = self._load_prompts_from_file(context)
        if not prompts_data:
            self.logger.error(
                "❌ Could not load any prompts to generate images. Halting generation."
            )
            return context
        # --- END OF FIX ---

        for garment_name, prompts in prompts_data.items():
            final_garment_prompt = prompts.get("final_garment")
            if not final_garment_prompt:
                self.logger.warning(
                    f"⚠️ No 'final_garment' prompt found for '{garment_name}'. Skipping."
                )
                continue

            await self._generate_and_save_image(
                final_garment_prompt, garment_name, context
            )

        self.logger.info("✅ All image generation tasks complete.")
        return context

    async def _generate_and_save_image(
        self, prompt: str, garment_name: str, context: RunContext
    ):
        """Generates a single image and saves it to the results directory."""
        self.logger.info(f"Generating image for: '{garment_name}'...")
        try:
            # FIXED: GPT Image API call with correct parameters
            response = await self.client.images.generate(
                model="gpt-image-1",
                prompt=prompt,
                size="1024x1024",
                quality="high",  # FIXED: Use "high" instead of "hd" for gpt-image-1
                n=1,
                # REMOVED: response_format parameter - not supported by gpt-image-1
                # GPT Image 1 always returns base64-encoded images by default
            )

            # --- START OF FIX: UPDATED DATA HANDLING FOR GPT IMAGE 1 ---
            # GPT Image 1 returns images differently than DALL-E 3
            if response.data and len(response.data) > 0:
                image_item = response.data[0]

                # GPT Image 1 returns base64 data directly in b64_json field
                if hasattr(image_item, "b64_json") and image_item.b64_json:
                    image_data_b64 = image_item.b64_json
                    image_data = base64.b64decode(image_data_b64)

                    slug = "".join(
                        c for c in garment_name.lower() if c.isalnum() or c in " -"
                    ).replace(" ", "-")
                    image_filename = f"{slug}.png"
                    image_path = Path(context.results_dir) / image_filename

                    with open(image_path, "wb") as f:
                        f.write(image_data)

                    self.logger.info(f"✅ Successfully saved image to '{image_path}'")

                    # Log revised prompt if available
                    if (
                        hasattr(image_item, "revised_prompt")
                        and image_item.revised_prompt
                    ):
                        self.logger.info(
                            f"📝 Revised prompt: {image_item.revised_prompt}"
                        )

                else:
                    # Handle case where no image data is returned (content filter, etc.)
                    revised_prompt = getattr(image_item, "revised_prompt", "N/A")
                    self.logger.error(
                        f"❌ GPT Image API call for '{garment_name}' was successful but returned no image data. "
                        f"This may be due to a content filter. Revised prompt was: '{revised_prompt}'"
                    )
            else:
                self.logger.error(
                    f"❌ GPT Image API call for '{garment_name}' returned no data."
                )
            # --- END OF FIX ---

        except Exception as e:
            self.logger.error(
                f"❌ GPT Image API call failed for '{garment_name}': {e}",
                exc_info=True,
            )

    def _load_prompts_from_file(self, context: RunContext) -> dict:
        """A fallback to load prompts directly from the JSON file if needed."""
        try:
            prompts_path = Path(context.results_dir) / settings.PROMPTS_FILENAME
            if prompts_path.exists():
                with open(prompts_path, "r", encoding="utf-8") as f:
                    return json.load(f)
            else:
                self.logger.warning(
                    f"⚠️ Prompts file not found at {prompts_path}. Cannot generate images."
                )
                return {}
        except Exception:
            self.logger.error(
                "❌ Could not load or parse prompts from file as a fallback.",
                exc_info=True,
            )
            return {}
